import Head from 'next/head'
import NavBar from '@/components/NavBar'
import { Inter } from 'next/font/google'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
// const userData = 
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation';

const Profile = () => {
  const [userData, setUserData] = useState(null)

  const { push } = useRouter();

  useEffect(()=>{
    const user = localStorage.getItem('user');
    if(!user){
        push('/login')
    }
    setUserData(JSON.parse(user))
    console.log(JSON.parse(user))
  }, [])

  if(!userData){
    return <></>
  }

  return (
    <>
      <Head>
        <title>Job Hunt - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <NavBar></NavBar>
        <h1>Profile</h1>
        <div>
            <p>Name: {userData?userData.name:''}</p>
            <p>Role: {userData?userData.role:''}</p>
        </div>
      </main>
    </>
  )
}

export default Profile
