import Head from 'next/head'
import NavBar from '@/components/NavBar'
import { Inter } from 'next/font/google'

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })
// const userData = 
import { useEffect, useState } from 'react'

const Login = () => {
  const [userData, setUserData] = useState({})

  useEffect(()=>{
    const user = localStorage.getItem('user');
    setUserData(JSON.parse(user))
    console.log(JSON.parse(user))
  }, [])

  return (
    <>
      <Head>
        <title>Job Hunt - Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <NavBar></NavBar>
        <h1>Profile</h1>
        <div>
            <p>Name: {userData.name}</p>
            <p>Role: {userData.role}</p>
        </div>
      </main>
    </>
  )
}

export default Login
