import Head from 'next/head'
import NavBar from '@/components/NavBar'
import LoginForm from '@/components/LoginForm'
import { Inter } from 'next/font/google'
import styles from '@/styles/Login.module.css'  
import { useEffect } from 'react'
import { useRouter } from 'next/navigation';

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({ subsets: ['latin'] })


export default function Users() {
  const { push } = useRouter();

  useEffect(()=>{
    const user = localStorage.getItem('user');
    const userData = JSON.parse(user)
    if(!userData){
      push('/login')
    }else if(userData.role === 'applicant'){
      push('/')
    }else if(userData.role === 'recruiter'){
      push('/post-job')
    }
  })

  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
      <NavBar></NavBar>
        <h1>Users</h1>
      </main>
    </>
  )
}
